---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager-receiver
  name: alertmanager-receiver
  namespace: alertmanager-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-receiver
  template:
    metadata:
      labels:
        app: alertmanager-receiver
    spec:
      containers:
      - image: quay.io/freedomben/alertmanager-receiver:latest
        name: alertmanager-receiver
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readiness
            port: 4567
          initialDelaySeconds: 5
          periodSeconds: 1
        env:
        - name: BASIC_OCP_DEMO_ENV
          value: master
            #- image: quay.io/freedomben/metals:latest
            #  name: metals
            #  imagePullPolicy: Always
            #  ports:
            #  - containerPort: 8443
            #    protocol: TCP
            #  envFrom:
            #  - configMapRef:
            #      name: alertmanager-receiver-certs
            #  - secretRef:
            #      name: alertmanager-receiver-server-key

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager-receiver
  name: alertmanager-receiver
  namespace: alertmanager-receiver
spec:
  ports:
  - name: 4567-tcp
    port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    app: alertmanager-receiver

      #---
      #apiVersion: route.openshift.io/v1
      #kind: Route
      #metadata:
      #  labels:
      #    app: alertmanager-receiver
      #  name: alertmanager-receiver
      #  namespace: alertmanager-receiver
      #spec:
      #  port:
      #    targetPort: 4567-tcp
      #  to:
      #    kind: Service
      #    name: alertmanager-receiver
      #    weight: 100
      #  wildcardPolicy: None
      #  tls:
      #    termination: edge
